### ISSUE TITLE
Was the SWIN encoder pre-trained?

### ISSUE THREAD

**Issue by fbragman** [IVRL/MulT#5]
Hi,

For the SWIN encoder in your model, did you use pretrained weights from ImageNet or did you train your network end-to-end from scratch?

Thanks

**Comment by deblinaml** [comment]
Hi, 
We used pre-trained weights from ImageNet as in the first Swin transformer model (https://github.com/microsoft/Swin-Transformer/blob/2cb103f2de145ff43bb9f6fc2ae8800c24ad04c6/models/swin_transformer_moe.py#L275). 
Thanks!
